development:
  app_id: '234766333302417'
  app_secret: 'd85897a9dd23facb50af923e879b3fc0'
  app_url: http://localhost:3000
  # https://dev.twitter.com/apps/1872270/show
  app_host: localhost:3000

production:
  app_id: ''
  app_secret: ''
  app_url: http://localhost:3000
